import { Account, Category, Goal, Investment, Transaction } from "./types";

export const initialCategories: Category[] = [
  // Despesas
  { id: "cat-1", name: "Alimentação & Mercado", type: "expense", icon: "Utensils", color: "#f97316" },
  { id: "cat-2", name: "Moradia & Contas", type: "expense", icon: "Home", color: "#3b82f6" },
  { id: "cat-3", name: "Transporte & Combustível", type: "expense", icon: "Car", color: "#eab308" },
  { id: "cat-4", name: "Lazer & Assinaturas", type: "expense", icon: "Film", color: "#a855f7" },
  { id: "cat-5", name: "Saúde & Farmácia", type: "expense", icon: "HeartPulse", color: "#ef4444" },
  { id: "cat-6", name: "Educação & Cursos", type: "expense", icon: "GraduationCap", color: "#06b6d4" },
  { id: "cat-7", name: "Compras & Vestuário", type: "expense", icon: "ShoppingBag", color: "#ec4899" },
  // Receitas
  { id: "cat-8", name: "Salário / Pro-labore", type: "income", icon: "Briefcase", color: "#10b981" },
  { id: "cat-9", name: "Freelance / Extra", type: "income", icon: "Zap", color: "#14b8a6" },
  { id: "cat-10", name: "Rendimentos & Dividendos", type: "income", icon: "TrendingUp", color: "#6366f1" },
];

export const initialAccounts: Account[] = [
  {
    id: "acc-1",
    name: "Conta Principal Nubank",
    type: "checking",
    institution: "Nubank",
    balance: 4850.50,
    color: "#820ad1",
  },
  {
    id: "acc-2",
    name: "Cartão Nubank Ultravioleta",
    type: "credit_card",
    institution: "Nubank",
    balance: -1640.20,
    credit_limit: 8000.00,
    available_limit: 6359.80,
    closing_day: 25,
    due_day: 5,
    color: "#4c0580",
  },
  {
    id: "acc-3",
    name: "Conta Itaú Corrente",
    type: "checking",
    institution: "Itaú",
    balance: 1220.00,
    color: "#ec7000",
  },
  {
    id: "acc-4",
    name: "Carteira Física",
    type: "cash",
    institution: "Dinheiro",
    balance: 280.00,
    color: "#10b981",
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: "tx-1",
    description: "Salário Mensal",
    amount: 7500.00,
    type: "income",
    category_id: "cat-8",
    account_id: "acc-1",
    date: "2026-10-01",
    status: "completed",
    is_recurring: true,
    recurrence_period: "monthly",
    tags: ["salario", "empresa"],
  },
  {
    id: "tx-2",
    description: "Aluguel & Condomínio",
    amount: 2200.00,
    type: "expense",
    category_id: "cat-2",
    account_id: "acc-1",
    date: "2026-10-02",
    status: "completed",
    is_recurring: true,
    recurrence_period: "monthly",
    tags: ["fixo", "casa"],
  },
  {
    id: "tx-3",
    description: "Supermercado Semanal",
    amount: 482.40,
    type: "expense",
    category_id: "cat-1",
    account_id: "acc-2",
    date: "2026-10-02",
    status: "completed",
    tags: ["alimentacao"],
  },
  {
    id: "tx-4",
    description: "Assinatura Netflix & Spotify",
    amount: 79.80,
    type: "expense",
    category_id: "cat-4",
    account_id: "acc-2",
    date: "2026-10-01",
    status: "completed",
    is_recurring: true,
    recurrence_period: "monthly",
    tags: ["streaming"],
  },
  {
    id: "tx-5",
    description: "Monitor Ultrawide (Parcela 2/6)",
    amount: 299.90,
    type: "expense",
    category_id: "cat-7",
    account_id: "acc-2",
    date: "2026-10-01",
    status: "completed",
    is_installment: true,
    installment_current: 2,
    installment_total: 6,
    tags: ["eletronicos", "trabalho"],
  },
];

export const initialGoals: Goal[] = [
  {
    id: "goal-1",
    title: "Reserva de Emergência (6 Meses)",
    target_amount: 30000.00,
    current_amount: 18500.00,
    type: "saving",
    deadline: "2026-12-31",
    color: "#10b981",
  },
  {
    id: "goal-2",
    title: "Viagem de Férias 2027",
    target_amount: 8000.00,
    current_amount: 3200.00,
    type: "saving",
    deadline: "2027-02-15",
    color: "#3b82f6",
  },
  {
    id: "goal-3",
    title: "Teto Mensal: Alimentação & Mercado",
    target_amount: 1500.00,
    current_amount: 482.40,
    category_id: "cat-1",
    type: "budget_limit",
    color: "#f97316",
  },
];

export const initialInvestments: Investment[] = [
  {
    id: "inv-1",
    name: "Tesouro Selic 2029 (Reserva)",
    type: "emergency_fund",
    institution: "Nubank / NuInvest",
    amount_invested: 15000.00,
    current_value: 16250.00,
    liquidity: "d+1",
    notes: "Principal parcela da reserva de emergência",
  },
  {
    id: "inv-2",
    name: "CDB 105% CDI Liquidez Diária",
    type: "emergency_fund",
    institution: "Banco Inter",
    amount_invested: 2000.00,
    current_value: 2250.00,
    liquidity: "immediate",
    notes: "Liquidez imediata para finais de semana",
  },
  {
    id: "inv-3",
    name: "ETF IVVB11 (S&P 500)",
    type: "equities",
    institution: "XP Investimentos",
    amount_invested: 5000.00,
    current_value: 5740.00,
    liquidity: "long_term",
    notes: "Exposição ao mercado global",
  },
];
